<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sunshine-PC" ignored="2" name="AssetionDemo" tests="2" failures="1" timestamp="01 Apr 2019 09:55:06 GMT" time="0.091" errors="0">
  <testcase name="demoSoftAssert_withAssertAll" time="0.049" classname="com.testcases.demo.SoftAssertDemo">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at com.testcases.demo.SoftAssertDemo.demoSoftAssert_withAssertAll(SoftAssertDemo.java:70)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- demoSoftAssert_withAssertAll -->
  <testcase name="dummyTest" time="0.004" classname="com.testcases.demo.dummy"/>
  <testcase name="demoNormalAssert" time="0.0" classname="com.testcases.demo.SoftAssertDemo">
    <ignored/>
  </testcase> <!-- demoNormalAssert -->
  <testcase name="demoFormalAsssert" time="0.0" classname="com.testcases.demo.SoftAssertDemo">
    <ignored/>
  </testcase> <!-- demoFormalAsssert -->
</testsuite> <!-- AssetionDemo -->
